sonar.projectKey=Soutien-Local
sonar.projectName=Soutien Local

sonar.host.url=http://localhost:9000
sonar.token=sqp_fe2d63b30dfd67049991d219b2a1e2cb82b3bfc9

sonar.sources=frontend/src,backend

sonar.exclusions=**/node_modules/**,**/vendor/**,**/storage/**

sonar.sourceEncoding=UTF-8